apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-k8s-app.fullname" . }}-config
  labels:
    {{- include "fastapi-k8s-app.labels" . | nindent 4 }}
data:
  environment: {{ .Values.environment | quote }}
  debug: {{ .Values.debug | quote }}
  log_level: {{ .Values.config.logLevel | quote }}
  enable_tracing: {{ .Values.config.enableTracing | quote }}
  enable_metrics: {{ .Values.config.enableMetrics | quote }}
