apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-k8s-app.fullname" . }}-secrets
  labels:
    {{- include "fastapi-k8s-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ .Values.secrets.secretKey | quote }}
  database_url: {{ .Values.secrets.databaseUrl | quote }}
  redis_url: {{ .Values.secrets.redisUrl | quote }}
